### ISSUE TITLE
Consistent Look And Feel

### ISSUE THREAD

**Issue by sam2b** [kyleb13/MobileAppsGroup1#103]
- [x] Top bar should remain present in Search.
- [x] Top bar should remain present in Account Settings.
- [x] Text label next to each text box.
- [x] Colors the same throughout the app.
- [x] Fonts the same throughout the app.
- [x] Button style the same throughout the app.
- [ ] Weather Activity maybe should model the Empty Activity template so there isn't a rogue back arrow in the top left corner.

**Comment by sam2b** [comment]
Tam finished.
