### ISSUE TITLE
Contacts - view, remove, invite

### ISSUE THREAD

**Issue by kyleb13** [kyleb13/MobileAppsGroup1#13]
- [x] View Connection Requests
   - [ ] The main screen should have two buttons, one that states 'View Incoming Requests' and the other stating 'View Outgoing Requests'.
   - [ ] Clicking incoming requests should lead to a screen that has a vertical linear layout format, with a list of connection requests from other people.
   - [ ] Clicking outgoing requests should lead to a screen with a list of connection requests to people.
   - [ ] Both screens should contain an 'Accept and a 'Reject' button next to each of the connections.
- [X] Remove an existing connection. (PR #79)
   - [X] Database query tested.
   - [X] This should be done through the 'View Existing Connections' screen mentioned earlier.
- [ ] Send invitations to email addresses using this app.
   - [ ] Has to be server side rather than client side.
   - [ ] Email must contain the @ character, with at least 1 letter before and after it.

**Comment by sam2b** [comment]
Completed remove an existing connection. (PR #79)
