### ISSUE TITLE
Login Screen(authentication)

### ISSUE THREAD

**Issue by kyleb13** [kyleb13/MobileAppsGroup1#14]
- [x] Must use email.
   - [x] contain the '@' character.
   - [x] contain at least 1 character before the '@'.
   - [x] contain at least 1 character after the '@'.
- [x] Server-side checks.
    - [x] First hash the password ???????
- [x] Client-side checks.
   - [x] no empty fields.
   - [x] username and password matches the data base, etc.
        * What does "etc." include?

**Comment by sam2b** [comment]
Tested, and works as expected by verifying the Heroku app log (status code 200) live while logging in.
