### ISSUE TITLE
Registration Screen

### ISSUE THREAD

**Issue by kyleb13** [kyleb13/MobileAppsGroup1#15]
Required from the user:
   - [ ] First and last name
   - [ ] Email (Verified)
   - [ ] Nickname (Used for in app display)
   - [ ] Password
- [ ] Server-side checks for valid credentials.
- [ ] Client-side checks for valid credentials.
- [ ] Define minimum requirements for password.
- [ ] Define minimum requirements for nickname.
        * What is a "nickname"????????????????

Upon registration attempt:
   - [ ] do not log the user in. ???????????????
   - [ ] display a page with progress animation (to inform the user of the verification process.

**Comment by sam2b** [comment]
Tested, and works as expected by verifying the Heroku app log live while registering, then performing a SQL query on the members table to see the new data.
