### ISSUE TITLE
Settings Options

### ISSUE THREAD

**Issue by sam2b** [kyleb13/MobileAppsGroup1#22]
- [x] option to Stay Logged in. (partially done in PR #50)
- [ ] choice of displaying Fname L. or nickname (partially done in PR #50)
- [x] able to change:  (partially done in PR #50)
   - [x] Fname
   - [x] Lname
   - [x] nickname
   - [x] email
   - [x] password.
- [x] option to log out. (partially done in PR #50)
- [ ] theme for colors.

**Comment by sam2b** [comment]
Partially complete in PR #50, only the mere layout components are in place.
