### ISSUE TITLE
Account Options

### ISSUE THREAD

**Issue by sam2b** [kyleb13/MobileAppsGroup1#23]
- [ ] Option to change email. (partially done in PR #50)
- [x] Option to change nickname. (PR #52)
- [x] Option to change first name. (PR #52)
- [x] Option to change last name. (PR #52)
- [X] Option to change password. (PR #53)
- [x] Option to soft delete account. (partially done in PR #50)
- [x] Add column named "deleted" to the database that defaults to 0.

**Comment by sam2b** [comment]
Partially complete in PR #50, only the layout components are in place.

**Comment by sam2b** [comment]
PR #52 Now able to change nickname, first name, and last name.  Includes pull from database to populate text fields.

**Comment by sam2b** [comment]
PR #53 Ability to change password fully functional.

**Comment by sam2b** [comment]
Done in PR #59
