### ISSUE TITLE
Account Settings - Ability to change password

### ISSUE THREAD

**Issue by sam2b** [kyleb13/MobileAppsGroup1#26]
- [X] Backend endpoint "changepassword" with SQL update command. (PR #50)
- [x] Front end ChangePasswordFragment (email address, current password, new password, confirm password) (PR #50)
- [x] Receive email from argument passed to ChangePasswordFragment. (PR #50)
- [x] Must first verify email address via JavaScript sending a special email with URL to click on.
-----------------------------
- [x] Sends email to the user with confirmation of password change. #49

**Comment by sam2b** [comment]
Blocked, waiting for @nguyek to complete #49

**Comment by sam2b** [comment]
Done in PR #59
